/*******************************************************************************
 * Name: Java class DataTypePanel.java
 * Project: PRISM Review Tool
 * Written by: Peter Ng, USGS, png@usgs.gov
 * 
 * This software is in the public domain because it contains materials that 
 * originally came from the United States Geological Survey, an agency of the 
 * United States Department of Interior. For more information, see the official 
 * USGS copyright policy at 
 * http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 * 
 * Date: first release date Feb. 2015
 ******************************************************************************/

package gov.usgs.smapp.smactions.datatypeactions;

import gov.usgs.smapp.SmCore;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author png
 */
public class DataTypePanel extends javax.swing.JPanel {

    /**
     * Creates new form DatatypePanel
     */
    public DataTypePanel() {
        initComponents();
        
        setupDataTypeButtonControls();
    }
    
    public JButton getAccelerationBtn() {return this.btnAcceleration;}
    public JButton getVelocityBtn() {return this.btnVelocity;}
    public JButton getDisplacementBtn() {return this.btnDisplacement;}
    public JButton getAllBtn() {return this.btnAll;}
    
    public void setPanelEnabledState(boolean state) {
        this.btnAcceleration.setEnabled(state);
        this.btnVelocity.setEnabled(state);
        this.btnDisplacement.setEnabled(state);
        this.btnAll.setEnabled(state);
    }
    
    private void setupDataTypeButtonControls()
    {
        BtnDataTypeActionListener btnDataTypeActionListener = 
            new BtnDataTypeActionListener();
        btnAcceleration.addActionListener(btnDataTypeActionListener);
        btnVelocity.addActionListener(btnDataTypeActionListener);
        btnDisplacement.addActionListener(btnDataTypeActionListener);
        btnAll.addActionListener(btnDataTypeActionListener);
    }
    
    private class BtnDataTypeActionListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent evt) {
        
            try {
                if (evt.getActionCommand().trim().startsWith("Acc"))
                {
                    btnAcceleration.setSelected(true);
                    btnVelocity.setSelected(false);
                    btnDisplacement.setSelected(false);
                    btnAll.setSelected(false);
                }
                else if (evt.getActionCommand().trim().startsWith("Vel"))
                {
                    btnAcceleration.setSelected(false);
                    btnVelocity.setSelected(true);
                    btnDisplacement.setSelected(false);
                    btnAll.setSelected(false);
                }
                else if (evt.getActionCommand().trim().startsWith("Dis"))
                {
                    btnAcceleration.setSelected(false);
                    btnVelocity.setSelected(false);
                    btnDisplacement.setSelected(true);
                    btnAll.setSelected(false);
                }
                else if (evt.getActionCommand().trim().startsWith("All"))
                {
                    btnAcceleration.setSelected(false);
                    btnVelocity.setSelected(false);
                    btnDisplacement.setSelected(false);
                    btnAll.setSelected(true);
                }

                // Update chart viewers by group.
                SmCore.updateChartViewPanels();
            }
            catch (Exception ex) {
                SmCore.addMsgToStatusViewer(ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbarDataType = new javax.swing.JToolBar();
        btnAcceleration = new javax.swing.JButton();
        btnVelocity = new javax.swing.JButton();
        btnDisplacement = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();

        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(100, 20));
        setLayout(new java.awt.BorderLayout());

        tbarDataType.setFloatable(false);
        tbarDataType.setRollover(true);

        btnAcceleration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/datatype_acc_16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnAcceleration, org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnAcceleration.text")); // NOI18N
        btnAcceleration.setToolTipText(org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnAcceleration.toolTipText")); // NOI18N
        btnAcceleration.setActionCommand(org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnAcceleration.actionCommand")); // NOI18N
        btnAcceleration.setFocusable(false);
        btnAcceleration.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceleration.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbarDataType.add(btnAcceleration);

        btnVelocity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/datatype_vel_16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnVelocity, org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnVelocity.text")); // NOI18N
        btnVelocity.setToolTipText(org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnVelocity.toolTipText")); // NOI18N
        btnVelocity.setActionCommand(org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnVelocity.actionCommand")); // NOI18N
        btnVelocity.setFocusable(false);
        btnVelocity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVelocity.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbarDataType.add(btnVelocity);

        btnDisplacement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/datatype_dis_16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnDisplacement, org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnDisplacement.text")); // NOI18N
        btnDisplacement.setToolTipText(org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnDisplacement.toolTipText")); // NOI18N
        btnDisplacement.setActionCommand(org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnDisplacement.actionCommand")); // NOI18N
        btnDisplacement.setFocusable(false);
        btnDisplacement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDisplacement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbarDataType.add(btnDisplacement);

        btnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/datatype_all_16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnAll, org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnAll.text")); // NOI18N
        btnAll.setToolTipText(org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnAll.toolTipText")); // NOI18N
        btnAll.setActionCommand(org.openide.util.NbBundle.getMessage(DataTypePanel.class, "DataTypePanel.btnAll.actionCommand")); // NOI18N
        btnAll.setFocusable(false);
        btnAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbarDataType.add(btnAll);

        add(tbarDataType, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceleration;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnDisplacement;
    private javax.swing.JButton btnVelocity;
    private javax.swing.JToolBar tbarDataType;
    // End of variables declaration//GEN-END:variables
}
