/*******************************************************************************
 * Name: Java class TemplatePanel.java
 * Project: PRISM Review Tool
 * Written by: Peter Ng, USGS, png@usgs.gov
 * 
 * This software is in the public domain because it contains materials that 
 * originally came from the United States Geological Survey, an agency of the 
 * United States Department of Interior. For more information, see the official 
 * USGS copyright policy at 
 * http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 * 
 * Date: first release date Feb. 2015
 ******************************************************************************/

package gov.usgs.smapp.smactions.fileactions;

import gov.usgs.smcommon.smclasses.SmGlobal;
import gov.usgs.smcommon.smclasses.SmPreferences;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JComboBox;

/**
 *
 * @author png
 */
public final class TemplatePanel extends javax.swing.JPanel {

    private final CBoxTemplateActionListener cboxTemplateActionListener = 
        new CBoxTemplateActionListener();
    
    /**
     * Creates new form TemplatePanel
     */
    public TemplatePanel() {
        initComponents();
       
        setCBoxTemplate(null);
    }

    public JComboBox<String> getCBoxTemplate() {
        return cboxTemplate;
    }
    
    public void setCBoxTemplate(String template) {
        
        try {
            // Temporarily remove cboxTemplate action listener.
            cboxTemplate.removeActionListener(cboxTemplateActionListener);

            // Clear template combo box.
            cboxTemplate.removeAllItems();

            File stationDir = new File(SmPreferences.General.getTemplatesRootDir() + File.separator + 
                SmPreferences.General.getStationTemplatesFolderName());

            if (stationDir.isDirectory())
            {
                cboxTemplate.addItem(SmGlobal.NO_SELECTION);

                File[] files = stationDir.listFiles();

                for (File file : files)
                {
                    if (file.isFile() && file.getName().endsWith(".xml"))
                    {
                        cboxTemplate.addItem(file.getName());
                    }
                }

                if (template == null || template.isEmpty()) {

                    cboxTemplate.setSelectedItem(SmPreferences.General.getTemplate());
                }
                else
                    cboxTemplate.setSelectedItem(template);
            }
        }
        catch (Exception ex) {
            throw ex;
        }
        finally {
            // Add back cboxTemplate action listener.
            cboxTemplate.addActionListener(cboxTemplateActionListener);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxTemplate = new javax.swing.JComboBox<>();
        lblTemplate = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(lblTemplate, org.openide.util.NbBundle.getMessage(TemplatePanel.class, "TemplatePanel.lblTemplate.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cboxTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblTemplate))
        );
    }// </editor-fold>//GEN-END:initComponents

    private class CBoxTemplateActionListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            SmPreferences.General.setTemplate(cboxTemplate.getSelectedItem().toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxTemplate;
    private javax.swing.JLabel lblTemplate;
    // End of variables declaration//GEN-END:variables
}
