/*******************************************************************************
 * Name: Java class SmFAS_ViewerTC.java
 * Project: PRISM Review Tool
 * Written by: Peter Ng, USGS, png@usgs.gov
 * 
 * This software is in the public domain because it contains materials that 
 * originally came from the United States Geological Survey, an agency of the 
 * United States Department of Interior. For more information, see the official 
 * USGS copyright policy at 
 * http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 * 
 * Date: first release date Feb. 2015
 ******************************************************************************/

package gov.usgs.smapp.smtopcomponents;

import javax.swing.JPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.Lookups;


/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//gov.usgs.smapp.smtopcomponents//SmFAS_ViewerTC//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "SmFAS_ViewerTC",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "gov.usgs.smapp.smtopcomponents.SmFAS_ViewerTC")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
@ActionReference(path = "Menu/Window", position = 50)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_SmFAS_ViewerTCAction",
        preferredID = "SmFAS_ViewerTC"
)
@Messages({
    "CTL_SmFAS_ViewerTCAction=Fourier Amplitude Spectrum Viewer",
    "CTL_SmFAS_ViewerTC=Fourier Amplitude Spectrum Viewer",
    "HINT_SmFAS_ViewerTC=Fourier Amplitude Spectrum Viewer"
})
public final class SmFAS_ViewerTC extends TopComponent {

    public SmFAS_ViewerTC() {
        initComponents();
        setName(Bundle.CTL_SmFAS_ViewerTC());
        setToolTipText(Bundle.HINT_SmFAS_ViewerTC());
        
        associateLookup(Lookups.singleton(this));
    }
    
    public JPanel getSpectralPanel() {return this.pnlSpectral;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpaneSpectral = new javax.swing.JScrollPane();
        pnlSpectral = new javax.swing.JPanel();

        pnlSpectral.setBackground(new java.awt.Color(255, 255, 255));
        pnlSpectral.setLayout(new javax.swing.BoxLayout(pnlSpectral, javax.swing.BoxLayout.PAGE_AXIS));
        scrollpaneSpectral.setViewportView(pnlSpectral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpaneSpectral)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpaneSpectral)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlSpectral;
    private javax.swing.JScrollPane scrollpaneSpectral;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
